[toolchain]
channel = "nightly-2025-12-01"
components = ["rustfmt", "clippy", "llvm-tools-preview", "miri"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-pc-windows-msvc"]
